name: Publish Nuget

on:
  push:
    tags: 
      - '*.*.**'

jobs:
  publish_nuget_package:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Version
        run: |
          sed -i -e 's/{{Version}}/${{github.ref_name}}/' ./TelegramBotSkeleton/TelegramBotSkeleton.csproj
      - name: Pack
        run: |
          dotnet pack ./TelegramBotSkeleton -c Release
      - name: Publish
        env:
          API_KEY: ${{secrets.nuget_api_key}}
        run: |
          dotnet nuget push ./bin/debug/*.nupkg --api-key $API_KEY --source https://api.nuget.org/v3/index.json
