name: Publish Nuget

on:
  push:
    tags: 
      - '*.*.**'

jobs:
  publish_nuget_package:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get path
        run: |
          echo "TelegramBotSkeleton.csproj found at: $(find . -name 'TelegramBotSkeleton.csproj')"
      - name: Set Version
        run: |
          sed -i '' "/<\/PackageId>/a\\                                                                                 
            <Version>${{github.ref_name}}<\/Version>" ./TelegramBotSkeleton/TelegramBotSkeleton.csproj
      - name: Pack
        run: |
          dotnet pack ./TelegramBotSkeleton -c Release -o .output
      - name: Publish
        env:
          API_KEY: ${{secrets.nuget_api_key}}
        run: |
          dotnet nuget push .output/*.nupkg --api-key $API_KEY --source https://api.nuget.org/v3/index.json
